from datetime import datetime
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, Spacer
from reports.report_styles import (
    ReportDocTemplate, PAGE_W, PAGE_H, MARGIN_LEFT, MARGIN_RIGHT,
    report_title_style, build_info_panel, build_data_table, spacer
)
from database.repositories.driver_repository import DriverRepository


class DriverReport:
    """Generates a report listing all active drivers."""

    def __init__(self, driver_repo: DriverRepository):
        self.driver_repo = driver_repo

    def generate(self, filepath: str, user_name: str = "System"):
        """Create the PDF report at the given filepath."""
        doc = ReportDocTemplate(filepath, user_name=user_name, pagesize=(PAGE_W, PAGE_H),
                                leftMargin=0, rightMargin=0, topMargin=0, bottomMargin=0)
        story = []

        # Report title
        story.append(Paragraph("DRIVER LIST REPORT", report_title_style))
        story.append(spacer(6 * mm))

        # Simple info panel with generated data
        info = {
            "Generated On:": datetime.now().strftime("%Y-%m-%d %H:%M"),
            "Generated By:": user_name,
        }
        avail_w = PAGE_W - MARGIN_LEFT - MARGIN_RIGHT
        info_table = build_info_panel(info, title="Report Information")
        info_table._argW[0] = 0.4 * avail_w
        info_table._argW[1] = 0.6 * avail_w
        story.append(info_table)
        story.append(spacer(8 * mm))

        # Fetch only Active drivers
        drivers = self.driver_repo.get_active_drivers_with_vehicle()

        # Table headers (no Status column)
        headers = ["Driver Name", "Designation", "Vehicle Number", "Route",
                   "Contact Number", "CNIC"]
        data_rows = []
        for d in drivers:
            data_rows.append([
                d.get("name", ""),
                d.get("designation", ""),
                d.get("vehicle_reg", "Not Assigned"),
                d.get("assigned_route", ""),
                d.get("contact_number", ""),
                d.get("cnic", ""),
            ])

        if data_rows:
            col_w = avail_w / len(headers)
            table = build_data_table(headers, data_rows, col_widths=[col_w]*len(headers))
            story.append(table)
        else:
            story.append(Paragraph("No active drivers found.", report_title_style))

        doc.build(story)