from datetime import datetime
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, Spacer
from reports.report_styles import (
    ReportDocTemplate, PAGE_W, PAGE_H, MARGIN_LEFT, MARGIN_RIGHT,
    report_title_style, build_info_panel, build_data_table, spacer
)
from database.repositories.vehicle_repository import VehicleRepository


class VehicleListReport:
    """Generates a report listing all active vehicles."""

    def __init__(self, vehicle_repo: VehicleRepository):
        self.vehicle_repo = vehicle_repo

    def generate(self, filepath: str, user_name: str = "System"):
        """Create the PDF report at the given filepath."""
        doc = ReportDocTemplate(filepath, user_name=user_name, pagesize=(PAGE_W, PAGE_H),
                                leftMargin=0, rightMargin=0, topMargin=0, bottomMargin=0)
        story = []

        # Report title
        story.append(Paragraph("VEHICLE LIST REPORT", report_title_style))
        story.append(spacer(6 * mm))

        # Simple info panel
        info = {
            "Generated On:": datetime.now().strftime("%Y-%m-%d %H:%M"),
            "Generated By:": user_name,
        }
        avail_w = PAGE_W - MARGIN_LEFT - MARGIN_RIGHT
        info_table = build_info_panel(info, title="Report Information")
        info_table._argW[0] = 0.4 * avail_w
        info_table._argW[1] = 0.6 * avail_w
        story.append(info_table)
        story.append(spacer(8 * mm))

        # Fetch vehicles
        vehicles = self.vehicle_repo.get_all_active()

        # Table headers
        headers = [
            "Registration Number", "Vehicle Type", "Model",
            "Fuel Type", "Engine Number", "Chassis Number", 
        ]
        data_rows = []
        for v in vehicles:
            data_rows.append([
                v.get("registration_number", ""),
                v.get("vehicle_type", ""),
                v.get("model", ""),
                v.get("fuel_type", ""),
                v.get("engine_number", ""),
                v.get("chassis_number", ""),
            ])

        if data_rows:
            col_w = avail_w / len(headers)
            table = build_data_table(headers, data_rows, col_widths=[col_w]*len(headers))
            story.append(table)
        else:
            story.append(Paragraph("No active vehicles found.", report_title_style))

        doc.build(story)