from datetime import datetime
from reportlab.platypus import Paragraph, Spacer
from reportlab.lib.units import cm, mm
from reports.report_styles import (
    ReportDocTemplate, PAGE_W,PAGE_H, MARGIN_LEFT, MARGIN_RIGHT,
    report_title_style, build_info_panel, build_data_table,
    build_summary_box, spacer
)
from database.repositories.vehicle_repository import VehicleRepository
from database.repositories.driver_repository import DriverRepository
from database.repositories.daily_log_repository import DailyLogRepository


class VehicleReport:
    """Generates a Vehicle Log Report for a specific vehicle and date range."""

    def __init__(
        self,
        vehicle_repo: VehicleRepository,
        driver_repo: DriverRepository,
        log_repo: DailyLogRepository,
    ):
        self.vehicle_repo = vehicle_repo
        self.driver_repo = driver_repo
        self.log_repo = log_repo

    def generate(
        self,
        filepath: str,
        vehicle_id: int,
        from_date: str,
        to_date: str,
        fuel_consumed: float,
        user_name: str = "System"
    ):
        """Create the PDF report at the given filepath."""
        # Create the document with custom template
        doc = ReportDocTemplate(filepath, user_name=user_name, pagesize=(PAGE_W, PAGE_H),
                                leftMargin=0, rightMargin=0, topMargin=0, bottomMargin=0)
        story = []

        # Report title
        story.append(Paragraph("VEHICLE LOG REPORT", report_title_style))
        story.append(spacer(8 * mm))  # spacing after title

        # 1. Fetch vehicle and driver info
        vehicle = self.vehicle_repo.get_by_id(vehicle_id)
        if not vehicle:
            raise ValueError("Vehicle not found.")
        driver = self.driver_repo.get_driver_by_vehicle(vehicle_id)
        driver_name = driver["name"] if driver else "Not Assigned"

        # 2. Fetch logs and filter by date range
        all_logs = self.log_repo.get_logs_for_vehicle(vehicle_id)
        # Filter logs within [from_date, to_date]
        filtered_logs = [
            log for log in all_logs
            if from_date <= log["log_date"] <= to_date
        ]
        # Sort by date and time ascending
        filtered_logs.sort(key=lambda x: (x["log_date"], x["from_time"]))

        # 3. Build information panel
        info = {
            "Vehicle Number:": vehicle["registration_number"],
            "Vehicle Type:": vehicle.get("vehicle_type", ""),
            "Driver:": driver_name,
            "From Date:": from_date,
            "To Date:": to_date,
            "Generated On:": datetime.now().strftime("%Y-%m-%d %H:%M"),
            "Generated By:": user_name,
        }
        # Available width for body elements
        avail_w = PAGE_W - MARGIN_LEFT - MARGIN_RIGHT
        info_table = build_info_panel(info, title="Vehicle Information")
        # Set column widths to 40% and 60% of available width
        info_table._argW[0] = 0.4 * avail_w
        info_table._argW[1] = 0.6 * avail_w
        story.append(info_table)
        story.append(spacer(8 * mm))

        # 4. Build logs table (if any)
        if filtered_logs:
            headers = [
                "Date", "From", "To", "Purpose / Route",
                "Meter Out", "Meter In", "Mileage", "Fuel",
                "Mobile Oil", "Remarks"
            ]
            data_rows = []
            for log in filtered_logs:
                data_rows.append([
                    log["log_date"],
                    log["from_time"],
                    log["to_time"],
                    log.get("purpose_route", ""),
                    str(log["meter_out"]),
                    str(log["meter_in"]),
                    str(log["mileage"]),
                    str(log.get("fuel", "")) if log.get("fuel") is not None else "",
                    str(log.get("mobile_oil", "")) if log.get("mobile_oil") is not None else "",
                    log.get("remarks", ""),
                ])
            # Equal column widths
            col_w = avail_w / len(headers)
            table = build_data_table(headers, data_rows, col_widths=[col_w]*len(headers))
            story.append(table)
            story.append(spacer(10 * mm))

            # 5. Compute summary
            first_log = filtered_logs[0]
            last_log = filtered_logs[-1]
            starting_meter = first_log["meter_out"]
            ending_meter = last_log["meter_in"]
            total_distance = ending_meter - starting_meter
            avg_mileage = round(total_distance / fuel_consumed, 2) if fuel_consumed > 0 else 0.0

            summary_items = [
                ("Starting Meter", str(starting_meter)),
                ("Ending Meter", str(ending_meter)),
                ("Total Distance", f"{total_distance:.2f}"),
                ("Fuel Consumed", f"{fuel_consumed:.2f} L"),
                ("Average Mileage", f"{avg_mileage:.2f} KM/L"),
            ]
            sum_table = build_summary_box(summary_items, title="Trip Summary")
            sum_table._argW[0] = 0.4 * avail_w
            sum_table._argW[1] = 0.6 * avail_w
            story.append(sum_table)
        else:
            story.append(Paragraph("No logs found for the selected date range.",
                                   report_title_style))  # reuse for message, but we can create a normal style

        # Build PDF
        doc.build(story)